import "@/styles/globals.css";
import "@mantine/core/styles.layer.css";
import "@mantine/charts/styles.layer.css";

import type { Metadata } from "next";
import { createTheme, ColorSchemeScript, MantineProvider } from "@mantine/core";

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Tinyboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="light" />
      </head>
      <body>
        <MantineProvider defaultColorScheme="light" theme={theme}>
          <main className="p-24 min-h-screen">{children}</main>
        </MantineProvider>
      </body>
    </html>
  );
}
